-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 19:05:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoGestordeSenhas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoGestordeSenhas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoGestordeSenhas` ;
USE `ProjetoGestordeSenhas` ;

-- -----------------------------------------------------
-- Table `ProjetoGestordeSenhas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoGestordeSenhas`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoGestordeSenhas`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoGestordeSenhas`.`Conta` (
  `idConta` INT NOT NULL AUTO_INCREMENT,
  `nomeConta` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NULL,
  `tipoConta` VARCHAR(20) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConta`),
  INDEX (`Usuario_idUsuario` ASC) ,
  FOREIGN KEY `fk_Conta_Usuario1`(`Usuario_idUsuario`) REFERENCES `ProjetoGestordeSenhas`.`Usuario` (`idUsuario`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoGestordeSenhas`.`Log_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoGestordeSenhas`.`Log_conta` (
  `nomeConta` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NULL,
  `tipoConta` VARCHAR(20) NOT NULL,
  `Conta_idConta` INT NOT NULL,
  INDEX `fk_Log_conta_Conta1_idx` (`Conta_idConta` ASC) ,
  CONSTRAINT `fk_Log_conta_Conta1`
    FOREIGN KEY (`Conta_idConta`)
    REFERENCES `ProjetoGestordeSenhas`.`Conta` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoGestordeSenhas`.`Log_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoGestordeSenhas`.`Log_usuario` (
  `nome` VARCHAR(50) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Log_usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Log_usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `ProjetoGestordeSenhas`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
